/**
 * pi-btw 插件界面汉化数据（btw-cn-data.ts）
 * 统一形式：英文原文保留 + 括号中文注释（紧凑的底部按键提示直接中文化）。
 * 给 AI 的 prompt（<side_question> 等注入文本）不在此文件。
 */

export const BTW_MAP: Array<[string, string]> = [
  ["title: \"Pi BTW\"", "title: \"Pi BTW（Pi 侧线程）\""],
  ["title: \"Resume BTW side thread\"", "title: \"Resume BTW side thread（恢复 BTW 侧线程）\""],
  ["title: \"Pi BTW Settings\"", "title: \"Pi BTW Settings（Pi BTW 设置）\""],
  ["title: \"Pi BTW Settings \\xB7 Read only\"", "title: \"Pi BTW Settings \\xB7 Read only（Pi BTW 设置 · 只读）\""],
  ["\"Start side thread\"", "\"Start side thread（开始侧线程）\""],
  ["\"Start from main thread tree\\u2026\"", "\"Start from main thread tree\\u2026（从主线程树开始）\""],
  ["\"Resume side thread\"", "\"Resume side thread（恢复侧线程）\""],
  ["\"Thinking level\"", "\"Thinking level（思考级别）\""],
  ["\"Remember thinking level changes\"", "\"Remember thinking level changes（记住思考级别更改）\""],
  ["\"Same as main thread\"", "\"Same as main thread（与主线程相同）\""],
  ["Open an empty side thread", "Open an empty side thread（打开空的侧线程）"],
  ["Choose context without switching the main branch", "Choose context without switching the main branch（选择上下文而不切换主分支）"],
  ["Continue an in-memory side thread", "Continue an in-memory side thread（继续内存中的侧线程）"],
  ["Choose pi-btw thinking level and fixed-level shortcut memory", "Choose pi-btw thinking level and fixed-level shortcut memory（选择 pi-btw 思考级别和固定级别快捷键记忆）"],
  ["Set the starting level for future pi-btw side threads. Currently ${currentMainThinkingLevel}.", "Set the starting level for future pi-btw side threads. Currently ${currentMainThinkingLevel}.（设置未来 pi-btw 侧线程的起始级别，当前：${currentMainThinkingLevel}。）"],
  ["Save shortcut changes for fixed thinking levels to pi-btw.json.", "Save shortcut changes for fixed thinking levels to pi-btw.json.（将固定思考级别的快捷键更改保存到 pi-btw.json。）"],
  ["User settings \\xB7 ${displaySettingsPath}", "User settings \\xB7 ${displaySettingsPath}（用户设置）"],
  ["Invalid settings file. Fix ${displaySettingsPath} before saving.", "Invalid settings file. Fix ${displaySettingsPath} before saving.（设置文件无效，保存前请修复 ${displaySettingsPath}。）"],
  ["The settings file is invalid.", "The settings file is invalid.（设置文件无效。）"],
  ["Pi BTW thinking level: ${value}.", "Pi BTW thinking level: ${value}.（Pi BTW 思考级别）"],
  ["Remember thinking level changes: ${value}.", "Remember thinking level changes: ${value}.（记住思考级别更改）"],
  ["Pi BTW settings were not saved; the previous value remains active: ${formatError3(error)}", "Pi BTW settings were not saved; the previous value remains active: ${formatError3(error)}（Pi BTW 设置未保存，仍使用之前的值）"],
  ["No main-thread entries are available", "No main-thread entries are available（没有可用的主线程条目）"],
  ["Selected entry has no text to copy", "Selected entry has no text to copy（所选条目没有可复制的文本）"],
  ["Copied selected message", "Copied selected message（已复制所选消息）"],
  ["Could not copy selected message: ${formatError4(error)}", "Could not copy selected message: ${formatError4(error)}（无法复制所选消息）"],
  ["\"Question cannot be empty\"", "\"Question cannot be empty（问题不能为空）\""],
  ["\"Untitled side thread\"", "\"Untitled side thread（未命名侧线程）\""],
  ["Ask a quick side question without adding it to the main conversation", "Ask a quick side question without adding it to the main conversation（快速提出侧边问题，不加入主对话）"],
  ["/btw requires interactive TUI mode", "/btw requires interactive TUI mode（/btw 需要交互式 TUI 模式）"],
  ["Resolving /btw model credentials...", "Resolving /btw model credentials...（正在解析 /btw 模型凭据...）"],
  ["\"Bring what back to the main thread?\"", "\"Bring what back to the main thread?（把什么带回主线程？）\""],
  ["\"Start from which question?\"", "\"Start from which question?（从哪个问题开始？）\""],
  ["The main editor already has a draft", "The main editor already has a draft（主编辑器已有草稿）"],
  ["Brought ${describeContent()} to the main editor. Review and submit when ready.", "Brought ${describeContent()} to the main editor. Review and submit when ready.（已带回主编辑器，确认后提交。）"],
  ["Appended ${describeContent()} to the existing main-editor draft. Review and submit when ready.", "Appended ${describeContent()} to the existing main-editor draft. Review and submit when ready.（已追加到现有主编辑器草稿，确认后提交。）"],
  ["Replaced the main-editor draft with ${describeContent()}. Review and submit when ready.", "Replaced the main-editor draft with ${describeContent()}. Review and submit when ready.（已替换主编辑器草稿，确认后提交。）"],
  ["btw \\u2022 Enter send \\u2022 Ctrl+R bring to main \\u2022 Ctrl+C exit", "btw \\u2022 Enter send \\u2022 Ctrl+R bring to main \\u2022 Ctrl+C exit（btw · Enter 发送 · Ctrl+R 带回主线程 · Ctrl+C 退出）"],
  ["btw \\u2022 Enter send \\u2022 Ctrl+C exit", "btw \\u2022 Enter send \\u2022 Ctrl+C exit（btw · Enter 发送 · Ctrl+C 退出）"],
  ["Enter steer \\u2022 Ctrl+C cancel", "Enter steer \\u2022 Ctrl+C cancel（Enter 转向 · Ctrl+C 取消）"],
  ["Ctrl+C cancel", "Ctrl+C cancel（Ctrl+C 取消）"],
  ["Empty \\u2022 Ctrl+C", "Empty \\u2022 Ctrl+C（空 · Ctrl+C）"],
  ["\"Selected: none\"", "\"Selected: none（已选：无）\""],
  ["Select text to bring to main", "Select text to bring to main（选择要带回主线程的文本）"],
  ["Select text first", "Select text first（请先选择文本）"],
  ["`Model: ", "`Model（模型）: "],
  ["`Thinking: ", "`Thinking（思考）: "],
  ["`Layout: ", "`Layout（布局）: "],
  ["Remember changes: ", "Remember changes（记住更改）: "],
  ["Copy on select: ", "Copy on select（选中即复制）: "],
  ["\"Exit shortcut\"", "\"Exit shortcut（退出快捷键）\""],
  ["\"Cycle thinking level shortcut\"", "\"Cycle thinking level shortcut（循环切换思考级别快捷键）\""],
  ["\"Bring to main shortcut\"", "\"Bring to main shortcut（带回主线程快捷键）\""],
  ["\"Inherit Pi\"", "\"Inherit Pi（继承 Pi）\""],
  ["\"Custom\"", "\"Custom（自定义）\""],
  ["\"Default\"", "\"Default（默认）\""],
  ["\"Fullscreen\"", "\"Fullscreen（全屏）\""],
  ["\"Settings\"", "\"Settings（设置）\""],
  ["Choose model, thinking, layout, keybindings, and selection copying", "Choose model, thinking, layout, keybindings, and selection copying（选择模型、思考、布局、快捷键与选中复制）"],
  ["Choose the model for future pi-btw side threads without changing the main session.", "Choose the model for future pi-btw side threads without changing the main session.（为未来的 pi-btw 侧线程选择模型，不改变主会话。）"],
  ["Use the main thread model when /btw starts.", "Use the main thread model when /btw starts.（/btw 启动时使用主线程模型。）"],
  ["This model identity cannot be stored in pi-btw.json.", "This model identity cannot be stored in pi-btw.json.（该模型标识无法存入 pi-btw.json。）"],
  ["Copy mouse selections immediately instead of with the configured copy key.", "Copy mouse selections immediately instead of with the configured copy key.（鼠标选中后立即复制，无需按复制键。）"],
  ["Use the full workspace or place BTW beside the live, click-to-focus main thread.", "Use the full workspace or place BTW beside the live, click-to-focus main thread.（占用整个工作区，或把 BTW 放在可点击切换的主线程旁边。）"],
  ["Edit a BTW-only key combination or restore its default. Ctrl+C always hard-cancels.", "Edit a BTW-only key combination or restore its default. Ctrl+C always hard-cancels.（编辑 BTW 专用快捷键或恢复默认。Ctrl+C 始终强制取消。）"],
  ["Ctrl+C always hard-cancels BTW.", "Ctrl+C always hard-cancels BTW.（Ctrl+C 始终强制取消 BTW。）"],
  ["Key combination", "Key combination（快捷键组合）"],
  ["\"Edit key combination\\u2026\"", "\"Edit key combination\\u2026（编辑快捷键组合…）\""],
  ["Restore default", "Restore default（恢复默认）"],
  ["Type a key name, not the shortcut itself. For example: ctrl+q or f6.", "Type a key name, not the shortcut itself. For example: ctrl+q or f6.（请输入按键名称，而不是直接按快捷键。例如：ctrl+q 或 f6。）"],
  ["Invalid key combination. Use a Pi key name such as ctrl+q or f6.", "Invalid key combination. Use a Pi key name such as ctrl+q or f6.（快捷键无效，请使用 Pi 按键名称，如 ctrl+q 或 f6。）"],
  ["The following context was brought back from a /btw side discussion.", "The following context was brought back from a /btw side discussion.（以下上下文来自 /btw 侧线程讨论。）"],
  ["Treat it as discussion context, not as work already completed.", "Treat it as discussion context, not as work already completed.（请视为讨论上下文，而非已完成的工作。）"],
  ["The side model returned a malformed response.", "The side model returned a malformed response.（侧线程模型返回了格式错误的响应。）"],
  ["The side model returned an error.", "The side model returned an error.（侧线程模型返回了错误。）"],
  ["No response received.", "No response received.（未收到响应。）"],
  ["No prior conversation context was available.", "No prior conversation context was available.（没有可用的先前对话上下文。）"],
  ["Continue the same side conversation.", "Continue the same side conversation.（继续同一个侧线程对话。）"],
  ["Answer this side question without modifying the main conversation.", "Answer this side question without modifying the main conversation.（回答这个侧边问题，不修改主对话。）"],
  ["Opening btw side thread\\u2026", "Opening btw side thread\\u2026（正在打开 btw 侧线程…）"],
  ["No selection to copy", "No selection to copy（没有可复制的内容）"],
  ["Copy failed", "Copy failed（复制失败）"],
  ["The main-thread tree picker closed", "The main-thread tree picker closed（主线程树选择器已关闭）"],
  ["The selected main-thread entry is no longer available", "The selected main-thread entry is no longer available（所选主线程条目已不可用）"],
  ["Side thread left", "Side thread left（侧线程在左）"],
  ["Side thread right", "Side thread right（侧线程在右）"],
  ["unknown model", "unknown model（未知模型）"],
  ["unknown provider", "unknown provider（未知提供商）"],
];
